### ISSUE TITLE
Mount point not empty

### ISSUE THREAD

**Issue by clement360** [dmikusa-pivotal/cf-ex-wordpress#6]
I pushed the app and received the following error:

ERR fusermount: entry for /home/vcap/app/htdocs/wp-content not found in /etc/mtab
2015-05-19T15:21:40.14-0400 [App/0]      OUT 19:21:40 sshfs   | fuse: mountpoint is not empty
2015-05-19T15:21:40.15-0400 [App/0]      OUT 19:21:40 sshfs   | fuse: if you are sure this is safe, use the 'nonempty' mount option

From manifest.yml
...
SSH_PATH: /mnt/filesync/homeMFC
SSH_KEY_NAME: id_rsa
SSH_OPTS: '["cache=yes", "kernel_cache", "compression=no", "large_read"]'

I ssh'd in to my remote storage ssh and there is nothing in this directory.
root@stage2fs:/mnt/filesync# ls
root@stage2fs:/mnt/filesync#

Is there a way to pass the nonempty option to fuse?

**Comment by dmikusa-pivotal** [comment]
A couple things here...

1.) It seems like fuse is having trouble mounting the remove file system.  It's saying that the location where it's trying to mount the remote file system is not empty.  The location where it tries to mount this is `/home/vcap/app/htdocs/wp-content`, which should always be empty since prior to mounting we move all of the files out of that directory.  Since it's not empty, it makes me think there is some other error happening prior to this.  

I would recommend setting the `BP_DEBUG` environment variable to `True`.  This will dump a bunch of additional information which might show you what else is failing.  If you need help reviewing it, post it as a gist and I can take a look.

2.) Your SSH_PATH, that looks incorrect.  That should be the path on the remote system that you want to mount.  `/mnt/filesync/homeMFC` doesn't exist though.  You're running `ls` on `/mnt/filesync` and it's not showing anything.  Try creating the "homeMFC" directory there or shortening SSH_PATH to just `/mnt/filesync`.

3.) If you want, you can pass the nonempty option to fuse.  To do that, you would just add `"nonempty"` to the list of SSH_OPTS.

Ex:

```
SSH_OPTS: '["cache=yes", "kernel_cache", "compression=no", "large_read", "nonempty"]'
```

This may cause other problems though as the remote file system is going to overlay the local file system and remove any files that were there.  This could cause files that are necessary to not be found.

Dan
